<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            [
                'id' => 1,
                'name' => 'Leke',
                'code' => 'ALL',
                'symbol' => 'Lek',
            ],
            [
                'id' => 2,
                'name' => 'Dollars',
                'code' => 'USD',
                'symbol' => '$',
            ],
            [
                'id' => 3,
                'name' => 'Afghanis',
                'code' => 'AFN',
                'symbol' => 'Ø‹',
            ],
            [
                'id' => 4,
                'name' => 'Pesos',
                'code' => 'ARS',
                'symbol' => '$',
            ],
            [
                'id' => 5,
                'name' => 'Guilders',
                'code' => 'AWG',
                'symbol' => 'Æ’',
            ],
            [
                'id' => 6,
                'name' => 'Dollars',
                'code' => 'AUD',
                'symbol' => '$',
            ],
            [
                'id' => 7,
                'name' => 'New Manats',
                'code' => 'AZN',
                'symbol' => 'Ð¼Ð°Ð',
            ],
            [
                'id' => 8,
                'name' => 'Dollars',
                'code' => 'BSD',
                'symbol' => '$',
            ],
            [
                'id' => 9,
                'name' => 'Dollars',
                'code' => 'BBD',
                'symbol' => '$',
            ],
            [
                'id' => 10,
                'name' => 'Rubles',
                'code' => 'BYR',
                'symbol' => 'p.',
            ],
            [
                'id' => 11,
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => 'â‚¬',
            ],
            [
                'id' => 12,
                'name' => 'Dollars',
                'code' => 'BZD',
                'symbol' => 'BZ$',
            ],
            [
                'id' => 13,
                'name' => 'Dollars',
                'code' => 'BMD',
                'symbol' => '$',
            ],
            [
                'id' => 14,
                'name' => 'Bolivianos',
                'code' => 'BOB',
                'symbol' => '$b',
            ],
            [
                'id' => 15,
                'name' => 'Convertible Marka',
                'code' => 'BAM',
                'symbol' => 'KM',
            ],
            [
                'id' => 16,
                'name' => 'Pula',
                'code' => 'BWP',
                'symbol' => 'P',
            ],
            [
                'id' => 17,
                'name' => 'Leva',
                'code' => 'BGN',
                'symbol' => 'Ð»Ð²',
            ],
            [
                'id' => 18,
                'name' => 'Reais',
                'code' => 'BRL',
                'symbol' => 'R$',
            ],
            [
                'id' => 19,
                'name' => 'Pounds',
                'code' => 'GBP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 20,
                'name' => 'Dollars',
                'code' => 'BND',
                'symbol' => '$',
            ],
            [
                'id' => 21,
                'name' => 'Riels',
                'code' => 'KHR',
                'symbol' => '៛',
            ],
            [
                'id' => 22,
                'name' => 'Dollars',
                'code' => 'CAD',
                'symbol' => '$',
            ],
            [
                'id' => 23,
                'name' => 'Dollars',
                'code' => 'KYD',
                'symbol' => '$',
            ],
            [
                'id' => 24,
                'name' => 'Pesos',
                'code' => 'CLP',
                'symbol' => '$',
            ],
            [
                'id' => 25,
                'name' => 'Yuan Renminbi',
                'code' => 'CNY',
                'symbol' => '¥',
            ],
            [
                'id' => 26,
                'name' => 'Pesos',
                'code' => 'COP',
                'symbol' => '$',
            ],
            [
                'id' => 27,
                'name' => 'ColÃ³n',
                'code' => 'CRC',
                'symbol' => 'â‚¡',
            ],
            [
                'id' => 28,
                'name' => 'Kuna',
                'code' => 'HRK',
                'symbol' => 'kn',
            ],
            [
                'id' => 29,
                'name' => 'Pesos',
                'code' => 'CUP',
                'symbol' => 'â‚±',
            ],
            [
                'id' => 30,
                'name' => 'Koruny',
                'code' => 'CZK',
                'symbol' => 'KÄ',
            ],
            [
                'id' => 31,
                'name' => 'Kroner',
                'code' => 'DKK',
                'symbol' => 'kr',
            ],
            [
                'id' => 32,
                'name' => 'Pesos',
                'code' => 'DOP',
                'symbol' => 'RD$',
            ],
            [
                'id' => 33,
                'name' => 'Dollars',
                'code' => 'XCD',
                'symbol' => '$',
            ],
            [
                'id' => 34,
                'name' => 'Pounds',
                'code' => 'EGP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 35,
                'name' => 'Colones',
                'code' => 'SVC',
                'symbol' => '$',
            ],
            [
                'id' => 36,
                'name' => 'Pounds',
                'code' => 'FKP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 37,
                'name' => 'Dollars',
                'code' => 'FJD',
                'symbol' => '$',
            ],
            [
                'id' => 38,
                'name' => 'Cedis',
                'code' => 'GHC',
                'symbol' => 'Â¢',
            ],
            [
                'id' => 39,
                'name' => 'Pounds',
                'code' => 'GIP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 40,
                'name' => 'Quetzales',
                'code' => 'GTQ',
                'symbol' => 'Q',
            ],
            [
                'id' => 41,
                'name' => 'Pounds',
                'code' => 'GGP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 42,
                'name' => 'Dollars',
                'code' => 'GYD',
                'symbol' => '$',
            ],
            [
                'id' => 43,
                'name' => 'Lempiras',
                'code' => 'HNL',
                'symbol' => 'L',
            ],
            [
                'id' => 44,
                'name' => 'Dollars',
                'code' => 'HKD',
                'symbol' => '$',
            ],
            [
                'id' => 45,
                'name' => 'Forint',
                'code' => 'HUF',
                'symbol' => 'Ft',
            ],
            [
                'id' => 46,
                'name' => 'Kronur',
                'code' => 'ISK',
                'symbol' => 'kr',
            ],
            [
                'id' => 47,
                'name' => 'Rupees',
                'code' => 'INR',
                'symbol' => 'Rp',
            ],
            [
                'id' => 48,
                'name' => 'Rupiahs',
                'code' => 'IDR',
                'symbol' => 'Rp',
            ],
            [
                'id' => 49,
                'name' => 'Rials',
                'code' => 'IRR',
                'symbol' => 'ï·¼',
            ],
            [
                'id' => 50,
                'name' => 'Pounds',
                'code' => 'IMP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 51,
                'name' => 'New Shekels',
                'code' => 'ILS',
                'symbol' => 'â‚ª',
            ],
            [
                'id' => 52,
                'name' => 'Dollars',
                'code' => 'JMD',
                'symbol' => 'J$',
            ],
            [
                'id' => 53,
                'name' => 'Yen',
                'code' => 'JPY',
                'symbol' => 'Â¥',
            ],
            [
                'id' => 54,
                'name' => 'Pounds',
                'code' => 'JEP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 55,
                'name' => 'Tenge',
                'code' => 'KZT',
                'symbol' => 'Ð»Ð²',
            ],
            [
                'id' => 56,
                'name' => 'Won',
                'code' => 'KPW',
                'symbol' => 'â‚©',
            ],
            [
                'id' => 57,
                'name' => 'Won',
                'code' => 'KRW',
                'symbol' => 'â‚©',
            ],
            [
                'id' => 58,
                'name' => 'Soms',
                'code' => 'KGS',
                'symbol' => 'Ð»Ð²',
            ],
            [
                'id' => 59,
                'name' => 'Kips',
                'code' => 'LAK',
                'symbol' => 'â‚­',
            ],
            [
                'id' => 60,
                'name' => 'Lati',
                'code' => 'LVL',
                'symbol' => 'Ls',
            ],
            [
                'id' => 61,
                'name' => 'Pounds',
                'code' => 'LBP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 62,
                'name' => 'Dollars',
                'code' => 'LRD',
                'symbol' => '$',
            ],
            [
                'id' => 63,
                'name' => 'Switzerland Francs',
                'code' => 'CHF',
                'symbol' => 'CHF',
            ],
            [
                'id' => 64,
                'name' => 'Litai',
                'code' => 'LTL',
                'symbol' => 'Lt',
            ],
            [
                'id' => 65,
                'name' => 'Denars',
                'code' => 'MKD',
                'symbol' => 'Ð´ÐµÐ',
            ],
            [
                'id' => 66,
                'name' => 'Ringgits',
                'code' => 'MYR',
                'symbol' => 'RM',
            ],
            [
                'id' => 67,
                'name' => 'Rupees',
                'code' => 'MUR',
                'symbol' => 'â‚¨',
            ],
            [
                'id' => 68,
                'name' => 'Pesos',
                'code' => 'MXN',
                'symbol' => '$',
            ],
            [
                'id' => 69,
                'name' => 'Tugriks',
                'code' => 'MNT',
                'symbol' => 'â‚®',
            ],
            [
                'id' => 70,
                'name' => 'Meticais',
                'code' => 'MZN',
                'symbol' => 'MT',
            ],
            [
                'id' => 71,
                'name' => 'Dollars',
                'code' => 'NAD',
                'symbol' => '$',
            ],
            [
                'id' => 72,
                'name' => 'Rupees',
                'code' => 'NPR',
                'symbol' => 'â‚¨',
            ],
            [
                'id' => 73,
                'name' => 'Guilders',
                'code' => 'ANG',
                'symbol' => 'Æ’',
            ],
            [
                'id' => 74,
                'name' => 'Dollars',
                'code' => 'NZD',
                'symbol' => '$',
            ],
            [
                'id' => 75,
                'name' => 'Cordobas',
                'code' => 'NIO',
                'symbol' => 'C$',
            ],
            [
                'id' => 76,
                'name' => 'Nairas',
                'code' => 'NGN',
                'symbol' => 'â‚¦',
            ],
            [
                'id' => 77,
                'name' => 'Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
            ],
            [
                'id' => 78,
                'name' => 'Rials',
                'code' => 'OMR',
                'symbol' => 'ï·¼',
            ],
            [
                'id' => 79,
                'name' => 'Rupees',
                'code' => 'PKR',
                'symbol' => 'â‚¨',
            ],
            [
                'id' => 80,
                'name' => 'Balboa',
                'code' => 'PAB',
                'symbol' => 'B/.',
            ],
            [
                'id' => 81,
                'name' => 'Guarani',
                'code' => 'PYG',
                'symbol' => 'Gs',
            ],
            [
                'id' => 82,
                'name' => 'Nuevos Soles',
                'code' => 'PEN',
                'symbol' => 'S/.',
            ],
            [
                'id' => 83,
                'name' => 'Pesos',
                'code' => 'PHP',
                'symbol' => 'Php',
            ],
            [
                'id' => 84,
                'name' => 'Zlotych',
                'code' => 'PLN',
                'symbol' => 'zÅ‚',
            ],
            [
                'id' => 85,
                'name' => 'Rials',
                'code' => 'QAR',
                'symbol' => 'ï·¼',
            ],
            [
                'id' => 86,
                'name' => 'New Lei',
                'code' => 'RON',
                'symbol' => 'lei',
            ],
            [
                'id' => 87,
                'name' => 'Rubles',
                'code' => 'RUB',
                'symbol' => 'Ñ€ÑƒÐ',
            ],
            [
                'id' => 88,
                'name' => 'Pounds',
                'code' => 'SHP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 89,
                'name' => 'Riyals',
                'code' => 'SAR',
                'symbol' => 'ï·¼',
            ],
            [
                'id' => 90,
                'name' => 'Dinars',
                'code' => 'RSD',
                'symbol' => 'Ð”Ð¸Ð',
            ],
            [
                'id' => 91,
                'name' => 'Rupees',
                'code' => 'SCR',
                'symbol' => 'â‚¨',
            ],
            [
                'id' => 92,
                'name' => 'Dollars',
                'code' => 'SGD',
                'symbol' => '$',
            ],
            [
                'id' => 93,
                'name' => 'Dollars',
                'code' => 'SBD',
                'symbol' => '$',
            ],
            [
                'id' => 94,
                'name' => 'Shillings',
                'code' => 'SOS',
                'symbol' => 'S',
            ],
            [
                'id' => 95,
                'name' => 'Rand',
                'code' => 'ZAR',
                'symbol' => 'R',
            ],
            [
                'id' => 96,
                'name' => 'Rupees',
                'code' => 'LKR',
                'symbol' => 'â‚¨',
            ],
            [
                'id' => 97,
                'name' => 'Kronor',
                'code' => 'SEK',
                'symbol' => 'kr',
            ],
            [
                'id' => 98,
                'name' => 'Dollars',
                'code' => 'SRD',
                'symbol' => '$',
            ],
            [
                'id' => 99,
                'name' => 'Pounds',
                'code' => 'SYP',
                'symbol' => 'Â£',
            ],
            [
                'id' => 100,
                'name' => 'New Dollars',
                'code' => 'TWD',
                'symbol' => 'NT$',
            ],
            [
                'id' => 101,
                'name' => 'Baht',
                'code' => 'THB',
                'symbol' => 'à¸¿',
            ],
            [
                'id' => 102,
                'name' => 'Dollars',
                'code' => 'TTD',
                'symbol' => 'TT$',
            ],
            [
                'id' => 103,
                'name' => 'Lira',
                'code' => 'TRY',
                'symbol' => 'â‚º',
            ],
            [
                'id' => 104,
                'name' => 'Liras',
                'code' => 'TRL',
                'symbol' => 'Â£',
            ],
            [
                'id' => 105,
                'name' => 'Dollars',
                'code' => 'TVD',
                'symbol' => '$',
            ],
            [
                'id' => 106,
                'name' => 'Hryvnia',
                'code' => 'UAH',
                'symbol' => 'â‚´',
            ],
            [
                'id' => 107,
                'name' => 'Pesos',
                'code' => 'UYU',
                'symbol' => '$U',
            ],
            [
                'id' => 108,
                'name' => 'Sums',
                'code' => 'UZS',
                'symbol' => 'Ð»Ð²',
            ],
            [
                'id' => 109,
                'name' => 'Bolivares Fuertes',
                'code' => 'VEF',
                'symbol' => 'Bs',
            ],
            [
                'id' => 110,
                'name' => 'Dong',
                'code' => 'VND',
                'symbol' => 'â‚«',
            ],
            [
                'id' => 111,
                'name' => 'Rials',
                'code' => 'YER',
                'symbol' => 'ï·¼',
            ],
            [
                'id' => 112,
                'name' => 'Zimbabwe Dollars',
                'code' => 'ZWD',
                'symbol' => 'Z$',
            ],
            [
                'id' => 113,
                'name' => 'Rupees',
                'code' => 'INR',
                'symbol' => 'â‚¹',
            ],
        ];
        foreach ($currencies as $currency) {
            Currency::updateOrcreate(['id' => $currency['id']], $currency);
        }
    }
}
