<?php

namespace Database\Seeders;

use App\Models\LimitSetting;
use Illuminate\Database\Seeder;

class LimitSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'bet_limit_id' => 1,
                'game_play_id' => 1,
                'big_min_bet' => 1,
                'big_max_bet' => 100,
                'small_min_bet' => 1,
                'small_max_bet' => 80,
                'three_c_min_bet' => 1,
                'three_c_max_bet' => 80,
                'three_a_min_bet' => 1,
                'three_a_max_bet' => 100,
                'game_limit_big' => 5000,
                'game_limit_small' => 5000,
                'game_limit_three_a' => 5000,
                'game_limit_three_c' => 5000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 14:19:08',
                'updated_at' => '2022-10-04 14:19:08',
            ],
            [
                'id' => 2,
                'bet_limit_id' => 1,
                'game_play_id' => 2,
                'big_min_bet' => 1,
                'big_max_bet' => 100,
                'small_min_bet' => 1,
                'small_max_bet' => 80,
                'three_c_min_bet' => 1,
                'three_c_max_bet' => 80,
                'three_a_min_bet' => 1,
                'three_a_max_bet' => 100,
                'game_limit_big' => 5000,
                'game_limit_small' => 5000,
                'game_limit_three_a' => 5000,
                'game_limit_three_c' => 5000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 14:19:08',
                'updated_at' => '2022-10-04 14:19:08',
            ],
            [
                'id' => 3,
                'bet_limit_id' => 1,
                'game_play_id' => 3,
                'big_min_bet' => 1,
                'big_max_bet' => 100,
                'small_min_bet' => 1,
                'small_max_bet' => 80,
                'three_c_min_bet' => 1,
                'three_c_max_bet' => 80,
                'three_a_min_bet' => 1,
                'three_a_max_bet' => 100,
                'game_limit_big' => 5000,
                'game_limit_small' => 5000,
                'game_limit_three_a' => 5000,
                'game_limit_three_c' => 5000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 14:19:08',
                'updated_at' => '2022-10-04 14:19:08',
            ],
            [
                'id' => 4,
                'bet_limit_id' => 2,
                'game_play_id' => 1,
                'big_min_bet' => 4000,
                'big_max_bet' => 400000,
                'small_min_bet' => 4000,
                'small_max_bet' => 400000,
                'three_c_min_bet' => 4000,
                'three_c_max_bet' => 400000,
                'three_a_min_bet' => 4000,
                'three_a_max_bet' => 400000,
                'game_limit_big' => 20000000,
                'game_limit_small' => 20000000,
                'game_limit_three_a' => 20000000,
                'game_limit_three_c' => 20000000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 14:53:05',
                'updated_at' => '2022-10-04 14:53:05',
            ],
            [
                'id' => 5,
                'bet_limit_id' => 2,
                'game_play_id' => 2,
                'big_min_bet' => 4000,
                'big_max_bet' => 400000,
                'small_min_bet' => 4000,
                'small_max_bet' => 400000,
                'three_c_min_bet' => 4000,
                'three_c_max_bet' => 400000,
                'three_a_min_bet' => 4000,
                'three_a_max_bet' => 400000,
                'game_limit_big' => 20000000,
                'game_limit_small' => 20000000,
                'game_limit_three_a' => 20000000,
                'game_limit_three_c' => 20000000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 14:53:05',
                'updated_at' => '2022-10-04 14:53:05',
            ],
            [
                'id' => 6,
                'bet_limit_id' => 2,
                'game_play_id' => 3,
                'big_min_bet' => 4000,
                'big_max_bet' => 400000,
                'small_min_bet' => 4000,
                'small_max_bet' => 400000,
                'three_c_min_bet' => 4000,
                'three_c_max_bet' => 400000,
                'three_a_min_bet' => 4000,
                'three_a_max_bet' => 400000,
                'game_limit_big' => 20000000,
                'game_limit_small' => 20000000,
                'game_limit_three_a' => 20000000,
                'game_limit_three_c' => 20000000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 14:53:05',
                'updated_at' => '2022-10-04 14:53:05',
            ],
            [
                'id' => 7,
                'bet_limit_id' => 3,
                'game_play_id' => 1,
                'big_min_bet' => 7,
                'big_max_bet' => 700,
                'small_min_bet' => 7,
                'small_max_bet' => 700,
                'three_c_min_bet' => 7,
                'three_c_max_bet' => 700,
                'three_a_min_bet' => 7,
                'three_a_max_bet' => 700,
                'game_limit_big' => 35000,
                'game_limit_small' => 35000,
                'game_limit_three_a' => 35000,
                'game_limit_three_c' => 35000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 15:14:21',
                'updated_at' => '2022-10-04 15:14:21',
            ],
            [
                'id' => 8,
                'bet_limit_id' => 3,
                'game_play_id' => 2,
                'big_min_bet' => 7,
                'big_max_bet' => 700,
                'small_min_bet' => 7,
                'small_max_bet' => 700,
                'three_c_min_bet' => 7,
                'three_c_max_bet' => 700,
                'three_a_min_bet' => 7,
                'three_a_max_bet' => 700,
                'game_limit_big' => 35000,
                'game_limit_small' => 35000,
                'game_limit_three_a' => 35000,
                'game_limit_three_c' => 35000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 15:14:21',
                'updated_at' => '2022-10-04 15:14:21',
            ],
            [
                'id' => 9,
                'bet_limit_id' => 3,
                'game_play_id' => 3,
                'big_min_bet' => 7,
                'big_max_bet' => 700,
                'small_min_bet' => 7,
                'small_max_bet' => 700,
                'three_c_min_bet' => 7,
                'three_c_max_bet' => 700,
                'three_a_min_bet' => 7,
                'three_a_max_bet' => 700,
                'game_limit_big' => 35000,
                'game_limit_small' => 35000,
                'game_limit_three_a' => 35000,
                'game_limit_three_c' => 35000,
                'deleted_at' => null,
                'created_at' => '2022-10-04 15:14:21',
                'updated_at' => '2022-10-04 15:14:21',
            ],
        ];
        foreach ($data as $info) {
            LimitSetting::updateOrcreate(['id' => $info['id']], $info);
        }
    }
}
