<?php

namespace Database\Seeders;

use App\Models\OddSetting;
use Illuminate\Database\Seeder;

class OddSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'market_id' => 1,
                'game_play_id' => 1,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:03:23',
                'updated_at' => '2022-10-04 17:10:11',
            ],
            [
                'id' => 2,
                'market_id' => 1,
                'game_play_id' => 2,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:03:23',
                'updated_at' => '2022-10-04 17:10:11',
            ],
            [
                'id' => 3,
                'market_id' => 1,
                'game_play_id' => 3,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:03:23',
                'updated_at' => '2022-10-04 17:10:11',
            ],
            [
                'id' => 4,
                'market_id' => 2,
                'game_play_id' => 1,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:10:17',
                'updated_at' => '2022-10-04 17:10:17',
            ],
            [
                'id' => 5,
                'market_id' => 2,
                'game_play_id' => 2,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:10:17',
                'updated_at' => '2022-10-04 17:10:17',
            ],
            [
                'id' => 6,
                'market_id' => 2,
                'game_play_id' => 3,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:10:17',
                'updated_at' => '2022-10-04 17:10:17',
            ],
            [
                'id' => 7,
                'market_id' => 3,
                'game_play_id' => 1,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:10:23',
                'updated_at' => '2022-10-04 17:10:23',
            ],
            [
                'id' => 8,
                'market_id' => 3,
                'game_play_id' => 2,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:10:23',
                'updated_at' => '2022-10-04 17:10:23',
            ],
            [
                'id' => 9,
                'market_id' => 3,
                'game_play_id' => 3,
                'big_first' => 3500,
                'big_second' => 1200,
                'big_third' => 600,
                'big_special' => 240,
                'big_consolation' => 80,
                'small_first' => 5000,
                'small_second' => 2400,
                'small_third' => 1200,
                'three_c_first' => 280,
                'three_c_second' => 280,
                'three_c_third' => 280,
                'three_a_first' => 840,
                'rebate_4d' => 30,
                'rebate_3d' => 30,
                'deleted_at' => null,
                'created_at' => '2022-10-04 17:10:23',
                'updated_at' => '2022-10-04 17:10:23',
            ],
        ];
        foreach ($data as $info) {
            OddSetting::updateOrcreate(['id' => $info['id']], $info);
        }
    }
}
